In [51]:
import numpy as np
from numpy import random

# Imposta il seme per il generatore di numeri casuali
np.random.seed(0)

# Creo 2 array 5x5 che rappresentano i consumi di edificio A e B
array_a = random.randint(1, 100, size=(5, 5))
array_b = random.randint(1, 100, size=(5, 5))

print(array_a, array_b)

# Calcola la somma dei consumi per ciascun edificio
consumo_a = np.sum(array_a)
consumo_b = np.sum(array_b)

print("Consumo totale edificio A:", consumo_a)
print("Consumo totale edificio B:", consumo_b)

# Calcolo il consumo max e min di edificio a e b

max_consumo_a = np.max(array_a)
min_consumo_a = np.min(array_a)

max_consumo_b = np.max(array_b)
min_consumo_b = np.min(array_b)


print("Consumo MAX edificio A:", max_consumo_a)
print("Consumo MIN edificio A:", min_consumo_a)

print("Consumo MAX edificio B:", max_consumo_b)
print("Consumo MIN edificio B:", min_consumo_b)

# Calcolo il consumo assoluto dei 2 edifici
# Somma elemento per elemento

somma_assoluta = array_a + array_b
print("Il consumo assoluto dei 2 edifici:\n", somma_assoluta)

# Calcola la moltiplicazione elemento per elemento dei due array

moltiplicazione_arr = array_a * array_b
print("La moltiplicazione tra i 2:\n", moltiplicazione_arr)


#  I consumi rilevati che sono maggiori di 50 kWh
# Array booleani per i consumi critici

consumi_critici_a = array_a > 50
consumi_critici_b = array_b > 50

print("Consumi critici edificio A:\n", consumi_critici_a)
print("Consumi critici edificio B:\n", consumi_critici_b)



# Questo era l’ultimo quesito per questo esercizio! Se ti va, puoi provare a utilizzare la libreria argparse per accettare un parametro da riga di comando che definisce la dimensione dell’array da usare (es. --size 5 per un array di forma (5, 5)). Considerala pure una domanda bonus e invia un messaggio vuoto se invece vuoi terminare qui.

[[45 48 65 68 68]
 [10 84 22 37 88]
 [71 89 89 13 59]
 [66 40 88 47 89]
 [82 38 26 78 73]] [[10 21 81 70 80]
 [48 65 83 89 50]
 [30 20 20 15 40]
 [33 66 10 58 33]
 [32 75 24 36 76]]
Consumo totale edificio A: 1483
Consumo totale edificio B: 1165
Consumo MAX edificio A: 89
Consumo MIN edificio A: 10
Consumo MAX edificio B: 89
Consumo MIN edificio B: 10
Il consumo assoluto dei 2 edifici:
 [[ 55  69 146 138 148]
 [ 58 149 105 126 138]
 [101 109 109  28  99]
 [ 99 106  98 105 122]
 [114 113  50 114 149]]
La moltiplicazione tra i 2:
 [[ 450 1008 5265 4760 5440]
 [ 480 5460 1826 3293 4400]
 [2130 1780 1780  195 2360]
 [2178 2640  880 2726 2937]
 [2624 2850  624 2808 5548]]
Consumi critici edificio A:
 [[False False  True  True  True]
 [False  True False False  True]
 [ True  True  True False  True]
 [ True False  True False  True]
 [ True False False  True  True]]
Consumi critici edificio B:
 [[False False  True  True  True]
 [False  True  True  True False]
 [False False False False False]
 